// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://corkvmhbdtvnabhlyqce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvcmt2bWhiZHR2bmFiaGx5cWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NjY4NjksImV4cCI6MjA1MjI0Mjg2OX0.l7C9u7QYQN3RKkKaCHckipzt9vysUQH9kj1QDwL1YDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);